group_order:
  - agentic
  - character
  - vocabulary
group_map:
  agentic: !Agentic
  character: !Character
    name: Character lessons
    lesson_order:
      - hiragana
      - hiragana-plus
      - katakana
      - katakana-plus
    lesson_map:
      hiragana:
        name: hiragana
        path: resources/hiragana.csv
      hiragana-plus:
        name: hiragana-plus
        path: resources/hiragana-plus.csv
      katakana:
        name: katakana
        path: resources/katakana.csv
      katakana-plus:
        name: katakana-plus
        path: resources/katakana-plus.csv
  vocabulary: !Vocabulary
    name: Vocabulary Lessons
    lesson_order:
      - hiragana-vocabulary
    lesson_map:
      hiragana-vocabulary:
        name: hiragana-vocabulary
        path: resources/hiragana-vocabulary.csv
